# Generated by Django 2.1.15 on 2019-12-23 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0008_auto_20191212_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=256)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('podcasts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='podcasts.Podcast')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
