# Generated by Django 2.1.15 on 2019-12-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20191212_1751'),
        ('profiles', '0004_auto_20191231_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_profile_friends_+', to='profiles.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='podcasts',
        ),
        migrations.AddField(
            model_name='profile',
            name='podcasts',
            field=models.ManyToManyField(null=True, to='podcasts.Podcast'),
        ),
    ]
