# Generated by Django 2.1.15 on 2020-03-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191231_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketCastsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=256)),
                ('usesPocketCasts', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='pocket_cast_settings',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.PocketCastsSettings'),
        ),
    ]
