# Generated by Django 2.1.15 on 2020-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200315_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body',
            field=models.TextField(default=None, max_length=240),
        ),
    ]
