# Generated by Django 2.1.15 on 2020-03-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200315_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketcastssettings',
            name='p',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
