# Generated by Django 2.1.15 on 2020-04-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200315_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocketcastssettings',
            name='p',
        ),
        migrations.AddField(
            model_name='pocketcastssettings',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcsettings', to='profiles.Profile'),
        ),
    ]
