# Generated by Django 2.1.15 on 2020-04-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200404_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocketCastsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, max_length=256)),
                ('usesPocketCasts', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcsettings', to='profiles.Profile')),
            ],
        ),
    ]
