# Generated by Django 2.1.15 on 2020-04-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20200404_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketcastssettings',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pocketcasts_settings', to='profiles.Profile'),
        ),
    ]
