# Generated by Django 2.1.15 on 2020-11-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20200404_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocketcastssettings',
            name='usesPocketCasts',
        ),
        migrations.AlterField(
            model_name='pocketcastssettings',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pocketcasts_settings', to='profiles.Profile'),
        ),
    ]
