# Generated by Django 2.1.15 on 2020-11-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201103_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketcastssettings',
            name='password',
            field=models.BinaryField(blank=True, max_length=256),
        ),
    ]
