# Generated by Django 2.1.15 on 2020-11-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20201103_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketcastssettings',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
