# Generated by Django 2.1.4 on 2019-12-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20191205_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
