# Generated by Django 2.1.4 on 2019-12-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Podcast',
        ),
    ]
