# Generated by Django 2.1.4 on 2019-12-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_auto_20191203_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
