# Generated by Django 2.1.15 on 2020-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20191212_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='podcast',
        ),
        migrations.AddField(
            model_name='comment',
            name='podcast_id',
            field=models.TextField(default='0', max_length=256),
        ),
    ]
