# Generated by Django 2.1.15 on 2020-01-17 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0011_auto_20200108_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='podcasts.Comment')),
                ('podcast', models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='podcasts.Podcast')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
