# Generated by Django 2.1.15 on 2020-01-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='podcasts.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='podcast',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='podcasts.Podcast'),
        ),
    ]
