# Generated by Django 2.1.15 on 2020-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0014_auto_20200314_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='commentz',
            new_name='comment',
        ),
    ]
