# Generated by Django 2.1.15 on 2020-04-04 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0015_auto_20200314_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=240)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('podcast', models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, related_name='foo', to='podcasts.Podcast')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
