# Generated by Django 2.1.15 on 2020-04-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_foo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foo',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
